### ISSUE TITLE
Cannot input fastq.gz, ref genome or genome annotation

### ISSUE THREAD

**Issue by thomchr** [alessandrolaferlita/RNAdetector#30]
Hi, I really like this software in principal and am trying to get it to work! When I open the software I can load my files - I'd like to do this using gz files though, are fastq.gz files not supported? Second, when I get to specifying reference genome/genome annotation there are no options from the dropdown box - is this related to files or is there a problem with my setup? Where I expect a list of species/genomes there is a blank line. Thanks for any advice!

**Comment by alaimos** [comment]
Hi, 
I appreciate your interest in RNAdetector.
Regarding your question, ".gz" files are supported by the software. When you select the FASTQ format, RNAdetector can automatically detect if you are using a compressed file or a regular FASTQ file.

For your second issue, did you install any reference genome from our repository (or load a custom genome) before trying analysis? Further details can be found here: [https://github.com/alessandrolaferlita/RNAdetector/wiki/Add-reference-and-annotation-files](https://github.com/alessandrolaferlita/RNAdetector/wiki/Add-reference-and-annotation-files).

**Comment by mjm269** [comment]
I am having the same problem it gives me an error when I try and upload a reference transcriptome.  It does not matter what mapper I chose or if I have the fasta file as .fa .fasta or anything else.

The error is below

Starting job.
Error: ErrorException: rename(/rnadetector/ws/storage/app/public/jobs/5//rnadetector/ws/storage/app/public/jobs/5/Eragrostis_tef.ASM97063v1.cdna.all.fasta,/rnadetector/ws/storage/app/references//teff/reference.fa): No such file or directory in /rnadetector/ws/app/Jobs/Types/ReferenceUploadJobType.php:293
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /rnadetector/ws/app/Jobs/Types/ReferenceUploadJobType.php(293): rename()
#2 /rnadetector/ws/app/Jobs/Request.php(72): App\Jobs\Types\ReferenceUploadJobType->handle()
#3 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\Request->handle()
#4 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#6 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#8 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#9 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#12 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#16 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\Queue\CallQueuedHandler->call()
#18 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\Queue\Jobs\Job->fire()
#19 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->process()
#20 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\Queue\Worker->runJob()
#21 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#22 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#26 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#28 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#29 /rnadetector/ws/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#30 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#31 /rnadetector/ws/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run()
#32 /rnadetector/ws/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#33 /rnadetector/ws/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#34 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#35 /rnadetector/ws/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run()
#36 /rnadetector/ws/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#37 {main}
